# Generated by Django 2.2 on 2020-09-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'table'), ('SW', 'couch'), ('OW', 'wardrobe'), ('D', 'desk')], max_length=2),
        ),
    ]
