# Generated by Django 2.2 on 2020-09-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200911_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'table'), ('SW', 'couch'), ('OW', 'wardrobe'), ('D', 'desk'), ('C', 'chair')], max_length=2),
        ),
    ]
