# Generated by Django 2.2 on 2020-09-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_address_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=0, default=39.99, max_digits=20),
        ),
    ]
